name: Run Poltergust Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-valid-example:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4

    - name: Install poltergust
      run: npm ci

    - name: Test the valid example ruleset
      run: npx poltergust ./examples/valid

    - name: Commit updated valid ruleset
      run: |
        git config --global user.name '👻poltergust'
        git config --global user.email 'poltergust@bot.github.com'
        git commit -am "👻 Auto-update valid ruleset"
        git push


  build-and-test-invalid-example:
    needs: build-and-test-valid-example
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4

    - name: Install poltergust
      run: npm ci

    - name: Test the invalid example ruleset (should exit 1)
      run: npx poltergust ./examples/invalid || (exitcode=$?; [ $exitcode -eq 1 ] || exit $exitcode)
      shell: bash